version: '3'

networks:
  diode_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1

services:
  send:
    image: diode:send
    build:
      context: .
      dockerfile: Dockerfile.send
    networks:
      diode_net:
        ipv4_address: 172.16.0.2
    ports:
      - "5000:5000"
    command:
      - "--from_tcp"
      - "172.16.0.2:5000"
      - "--to_udp"
      - "172.16.0.3:6000"
      - "--bandwidth_limit"
      - "10"

  receive:
    image: diode:receive
    build:
      context: .
      dockerfile: Dockerfile.receive
    networks:
      diode_net:
        ipv4_address: 172.16.0.3
    command:
      - "--from_udp"
      - "172.16.0.3:6000"
      - "--to_tcp"
      - "172.16.0.1:7000"

