mtu = 9000
ports = [5001, 5002, 5003, 5004]
block = 300_000
repair = 3
max_clients = 2
hash = false
flush = false
heartbeat = 10

[send]
log = "INFO"
to = "127.0.0.1"
to_bind = "0.0.0.0:0"
mode = "mmsg"
prometheus_listen = "127.0.0.1:9001"

[[send.from]]
tcp = "127.0.0.1:4000"

[[send.from]]
unix = "/tmp/source_to_tcp_port_6001"

[receive]
log = "INFO"
from = "127.0.0.1"
mode = "mmsg"
queue_size = 4096
reset_timeout = 2
abort_timeout = 60
prometheus_listen = "127.0.0.1:9002"

[[receive.to]]
unix = "/tmp/dest_from_tcp_port_4000"

[[receive.to]]
tcp = "127.0.0.1:6001"

