mtu = 9000
ports = [5001, 5002, 5003, 5004, 5005]
block = 220_000
repair = 1
max_clients = 1


[send.tls]
key = "/tmp/ca/intermediate/private/server.key.pem"
certificate = "/tmp/ca/intermediate/certs/server.cert.pem"
ca = "/tmp/ca/intermediate/certs/ca-chain.cert.pem"
#tls_min = "tls1_3"
#tls_method = "mozilla_modern_v5"
#ciphers = "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256"
#groups = "secp521r1:secp384r1:brainpoolP512r1tls13:brainpoolP384r1tls13:brainpoolP256r1tls13"

[send]
from = [ "tls:127.0.0.1:4000" ]

[receive.tls]
key = "/tmp/ca/intermediate/private/client.key.pem"
certificate = "/tmp/ca/intermediate/certs/client.cert.pem"
ca = "/tmp/ca/intermediate/certs/ca-chain.cert.pem"
#tls_min = "tls1_3"
#tls_method = "mozilla_modern_v5"
#ciphers = "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256"
#groups = "secp521r1:secp384r1:brainpoolP512r1tls13:brainpoolP384r1tls13:brainpoolP256r1tls13"

[receive]
to = [ "tls:127.0.0.1:7000" ]


