name: Clippy

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy-check:
    name: Run clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install just

      - name: Update rust
        run: rustup update

      - name: Run clippy
        run: just clippy
