name: Doc
on:
  push:
    tags: [ v* ]

jobs:
  doc-build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install just

      - name: Prepare
        run: pip install sphinx sphinx_rtd_theme

      - name: Build
        run: just doc

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: doc/_build
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
