name: Rust

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --workspace
    - name: Run tests
      run: cargo test
    - name: Install behave
      run: sudo apt install python3-behave python3-fusepy
    - name: Run integration tests
      run: behave --tags=~fail
