name: Tests

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Get admin permissions for tc
        run: sudo setcap cap_net_admin+ep /usr/sbin/tc

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install python3-pip python3-virtualenv just

      - name: Update rust
        run: rustup update

      - name: Create virtualenv
        run: virtualenv venv

      - name: Install python packages
        run: |
          source venv/bin/activate
          pip install behave psutil

      - name: Run tests
        run: |
          source venv/bin/activate
          just test
